### ISSUE TITLE
noise on stderr

### ISSUE THREAD

**Issue by regular** [kripken/emscripten-fastcomp#109]
I need to interpret my emsciptified program's output (it's llvm-as and I'd like to parse the error messages)

Currently, Module.printErr is a bit noisy, I am getting messages like

    pre-main prep time: 5 ms
    Calling stub instead of sigprocmask()
    ...

is there a way to get the program's stderr output without the added messages by emscripten's runtime?

**Comment by kripken** [comment]
Not directly. `Module.printErr` is called by both libc stderr and by various places in emscripten code.

But I believe those specific messages are only shown in `ASSERTIONS` builds, and so should not be seen in normal optimized builds. If you still see them when assertions are off or when `-O2` or above, then we should put those behind `ASSERTIONS`.

**Comment by regular** [comment]
Neither -O2 nor -O3 nor -s ASSERTIONS=0 helped. 

```
emcc (Emscripten gcc/clang-like replacement) 1.33.0 (commit 2ba610ea8bbcaaf1d769eec9c056089eac62aea6
```

**Comment by regular** [comment]
Just realised: this is the wrong repo.
I'm working on a PR.
