### ISSUE TITLE
Update the NaCl code?

### ISSUE THREAD

**Issue by tomaka** [kripken/emscripten-fastcomp#137]
I just ran into a very nasty bug with the `NaCl/SimplifyStructRegSignatures` pass that didn't remove the `pure` attribute (its real name is `readnone` I think) from functions after changing their signatures to not be pure anymore. This ended up causing a lot of test failures in the Rust tests suite.

It turns out this bug is already fixed in [the PNaCl repository](https://chromium.googlesource.com/native_client/pnacl-llvm/+/master/lib/Transforms/NaCl/SimplifyStructRegSignatures.cpp).

It would be nice to eventually update the emscripten code to be up-to-date with NaCl. I'm not familiar enough with how all this works to do this myself (I received a lot of help from folks on IRC just to diagnose the problem).

**Comment by kripken** [comment]
Sadly, this has become tricky. We used to literally use PNaCl as our upstream, but they decided to change their development plans, from rapid updates from LLVM to an unspecified rate, that was in practice not frequent. We need to be closer to upstream LLVM, so we switched to LLVM.

That means it's not trivial for us to update the PNaCl passes, we are essentially maintaining a fork of them. In practice, they are not under heavy development so this hasn't hurt us much, really, yours is the first bugfix we'll be fetching from them.

Do you have a testcase showing the issue? I can do this using that.

**Comment by tomaka** [comment]
I'll just ping @eddyb here.

Does the testcase need to be C/C++? I think it can be reproduced with pointers to member functions but I'm not sure.

**Comment by kripken** [comment]
LLVM IR is fine too. Preferably as small as possible regardless of language.

**Comment by eddyb** [comment]
Checking that a function call returning `{i32, i32}` (and originally `readnone` or `readonly`) is still present in the asm.js output should do.

**Comment by tomaka** [comment]
I don't know how convenient that is, but here is the test case I used to find the bug: https://gist.github.com/tomaka/6f3762d434cfde466376

In `lib.ll` the function named `hello` calls `get`, which is located in `sublib.ll`. The `SimplifyStructRegSignatures` modifies the signature the `get`, and the call to `get` ends up being totally dropped from the body of `hello` in the dead code removal pass.

**Comment by kripken** [comment]
I'm confused.

1. Why are those 2 separate files? Does the bug happen after linking them too?
2. There seems to be no connection between the two files. `sublib` defines `ZN3get20hd36e917fe4860cc7haaE`, while the other calls `ZN3get20h05af50f9733c2d54haaE`, but those aren't the same.

**Comment by tomaka** [comment]
Arg. There's a bug in rustc that causes the `get` function to be inlined if I put it in the same compilation unit as `hello`.
Problem number 2 is weird, but I'm compiling in a way in which you're not intended to compile.

I'll try to get another test case.

**Comment by eddyb** [comment]
@tomaka No, it's not a rustc bug, that's just how LLVM works. You have a pure function, which gets replaced by its return value.

To fix problem number 2, you can use `#[no_mangle]`, I think.

**Comment by tomaka** [comment]
@eddyb wrote a better test case: https://gist.github.com/tomaka/b8fa161cc407562ae5b0

Expected output is `*1234,5678*`.
Buggy output is `*0,0*` (content of uninitialized memory).

**Comment by eddyb** [comment]
The `*0,0*` output could be changed, though, to anything you want (they're two stores of `0` in the IR).

**Comment by kripken** [comment]
Thanks, that's very helpful. Ok, I've picked out the relevant upstream fix and pushed to incoming, also added that test.

**Comment by tomaka** [comment]
Thanks!
