### ISSUE TITLE
Memory leaks in Relooper?

### ISSUE THREAD

**Issue by hobby8** [kripken/emscripten-fastcomp#145]
I hope it's the right place for this issue. I'm using Relooper in a standalone project on a simple scenario and getting memory leaks, exactly as anticipated in [the code](https://github.com/kripken/emscripten-fastcomp/blob/master/lib/Target/JSBackend/Relooper.cpp#L157).

Is there a more elegant way to fix these leaks than simply tracking which branches have been deleted during the algorithm and cleaning up the remaining ones?

Problem scenario:
```c++
bb[0] = new Block("...", nullptr);
bb[1] = new Block("...", nullptr);
bb[2] = new Block("...", nullptr);
bb[1]->AddBranchTo(bb[2], nullptr, nullptr)
bb[1]->AddBranchTo(bb[0], "...", nullptr)
bb[2]->AddBranchTo(bb[0], nullptr, nullptr)
relooper.AddBlock(bb[0]);
relooper.AddBlock(bb[1]);
relooper.AddBlock(bb[2]);
relooper.Calculate(bb[1]);
```

**Comment by kripken** [comment]
I noticed that as well in the binaryen port of the relooper, you can probably do something similar [to the code there](https://github.com/WebAssembly/binaryen/blob/master/src/cfg/Relooper.cpp#L124).

I didn't have time to understand why this leak exists, it's probably something to do with unreachable code and a bug in detecting it. When I have time I'll look into this more.

**Comment by hobby8** [comment]
Thanks, found the issue and submitted a PR.
It seems that the WebAssembly version is already fixed ([code](https://github.com/kripken/emscripten-fastcomp/blob/master/lib/Target/WebAssembly/Relooper.cpp#L257)).

Thank you for keeping this algorithm so easily reusable!

**Comment by kripken** [comment]
With your PR merged I think we can close this issue. Thanks!
