### ISSUE TITLE
Prebuilt Binaries

### ISSUE THREAD

**Issue by caffinatedmonkey** [kripken/emscripten-fastcomp#159]
Building this project takes about hours on my machine (Linux). This is makes the `./emsdk install latest` command very slow. This could be fixed by providing prebuilt assets. I tried setting up a [travis-ci job](https://travis-ci.org/caffinatedmonkey/emsdk/jobs/178381638) automate prebuilt assets, but it timed out. I couldn't find any other free CI providers. Does anyone have any ideas for where/how we could automate builds?

Thanks for this awesome project btw!

**Comment by caffinatedmonkey** [comment]
Relevant Fork + File: https://github.com/caffinatedmonkey/emscripten-fastcomp/blob/ci/.travis.yml

**Comment by kripken** [comment]
See https://github.com/kripken/emscripten/issues/4682, there is now a new way to do this. Feedback welcome.
