### ISSUE TITLE
Code using 16-bit signed integers generates broken JS output

### ISSUE THREAD

**Issue by OleksandrChekhovskyi** [kripken/emscripten-fastcomp#161]
This problem has been encountered when using FreeType, in a function `FT_GlyphLoader_Add`, that contains a code like this:
```
    FT_UInt       n_curr_contours; // <-- this is 32bit unsigned int
...
    n_curr_contours = current->outline.n_contours; // <-- this is 16bit signed int
```
This code gets transformed into:
```
 $n_contours = $loader + 56 | 0;
 $0 = HEAP32[$n_contours >> 2] | 0;
 $conv = $0 << 16 >> 16;
```
which in case of large enough value produced broken result: `40680 << 16 >> 16 = -24856`.
This broke the loop logic afterwards.

I can't see anything in asm.js spec about this kind of cast, so is this really the way to do it?

Relevant generator code seems to be here:
https://github.com/kripken/emscripten-fastcomp/blob/dfcb07a871addf339ffac17e606e16e97e8c5f71/lib/Target/JSBackend/JSBackend.cpp#L1014

**Comment by OleksandrChekhovskyi** [comment]
I just realized that value `40680` is already out of bounds, and it was only that way because it read it from heap as 32bit integer, and then truncated with shifts to 16bit integer.

I just compared it with native code, and the value was "6" in that case, so the data or pointer somewhere must have got corrupted. There might be an issue with codegen, but probably not here - I'll investigate further.

**Comment by kripken** [comment]
Yeah, that pattern is a load of a 32-bit value, then a truncation to 16-bit. It's a signed truncation, performed by pushing it all to the left, then all the way back, so that the sign bit is extended, which we need as the variable we store in is 32-bit.

**Comment by OleksandrChekhovskyi** [comment]
Further investigation revealed that corruption was happening due to abuse of function pointers in FreeType (signature mismatch). Patch submitted upstream at https://savannah.nongnu.org/patch/?9180

Therefore, no problem here.

**Comment by kripken** [comment]
Good, glad you found the issue.
