### ISSUE TITLE
em++ memcopies objects that are not trivially copyable

### ISSUE THREAD

**Issue by mkl-ableton** [kripken/emscripten-fastcomp#175]
This issue was moved from https://github.com/kripken/emscripten/issues/5114

The following code breaks in the line `tested = make_tested();`. The generated code constructs a `Tested` object on the stack inside `make_tested` and then returns the constructed object's data (thereby changing the object's address) without calling a copy constructor. Using the same version of clang but compiling for the target x86_64-apple-darwin15.6.0, the code generated for `make_tested` instead constructs the object at an address provided by the caller.

The problem disappears when increasing the object's size.

This happens using https://github.com/kripken/emscripten-fastcomp-clang/commit/d4b1e0785f1ee15ab78207de4380e82e3407c6ea and https://github.com/kripken/emscripten-fastcomp/commit/09aaa022c31e247bfb7b00882372733e6b27f007

test.cpp
```#include <vector>
#include <cassert>

class Tested;

std::vector<Tested*> objects_that_were_constructed;

class Tested
{
public:
  Tested() {
    objects_that_were_constructed.push_back(this);
  }

  Tested(const Tested& other) {
    objects_that_were_constructed.push_back(this);
  }

  Tested& operator=(const Tested& other) {
    auto constructor_of_other_was_called =
     objects_that_were_constructed.end() != std::find(objects_that_were_constructed.begin(), objects_that_were_constructed.end(), &other);

    assert(constructor_of_other_was_called);

    // Leaving out the actual assignment code, as it's not relevant

    return *this;
  }

private:
  int state0 = 0;

  // Uncommenting the following line makes the test work
  // int state1 = 0;
};

Tested make_tested()
{
  return Tested();
}


int main() {
  Tested tested;
  tested = make_tested();

  return 0;
}
```

**Comment by kripken** [comment]
Very strange. Perhaps this is undefined behavior in C++? I don't know enough to tell.

**Comment by mkl-ableton** [comment]
I had a look at the code to see where the above mentioned differences in IR between x86_64-apple-darwin15.6.0 and asmjs-apple-emscripten come from.

As explained above, `make_tested` constructs the object in a pointer provided by the caller on x86.
 This is achieved by classifying the return type as`ABIArgInfo::Kind::Indirect`. This classification is performed by `ItaniumCXXABI::classifyReturnType`, which uses `Indirect` for types with non-trivial destructors/copy constructors.

`EmscriptenABIInfo::classifyReturnType` has an optimization for single-element structs, for which it uses `ABIArgInfo::Kind::Direct`. I'm also no C++ expert, but judging from the implementation of `ItaniumCXXABI::classifyReturnType`, I guess that this optimization performed by `EmscriptenABIInfo::classifyReturnType` is wrong.

Removing this optimization does fix the test that I provided.

**Comment by kripken** [comment]
Thanks for the investigation! Yes, I think that's all correct. Inspecting the code, we followed wasm's ABI there, and looks like they indeed fixed a bug there, so we should just update with that. Fix in https://github.com/kripken/emscripten-fastcomp-clang/pull/16

**Comment by kripken** [comment]
Fixed by that PR.
