### ISSUE TITLE
EMCC_FAST_COMPILER=0 does not work

### ISSUE THREAD

**Issue by promethe42** [kripken/emscripten-fastcomp#19]
Hello,

on my config (Ubuntu 13.10 Linux 3.11 64 bits), setting EMCC_FAST_COMPILER to 0 does not disable fastcomp: I still get fastcomp related warnings for exceptions.

However, unsetting the variable like this:
```
unset EMCC_FAST_COMPILER
```

works just fine and fastcomp is not used anymore.

I think this is not the documented behavior:

https://github.com/kripken/emscripten/wiki/LLVM-Backend

Regards,

**Comment by waywardmonkeys** [comment]
This option is no longer supported, so this bug can be closed.
