### ISSUE TITLE
MinGW Build Failure ('::SHGetKnownFolderPath' has not been declared)

### ISSUE THREAD

**Issue by osen** [kripken/emscripten-fastcomp#190]
Hi,

I was trying to build fastcomp using:
- mingw32/4.8.1 (gcc version 4.8.1 (rev5, Built by MinGW-W64 project))
- cmake version 3.7.1

and I came across this build failure:
https://pastebin.com/BzHR5Ppw

I am using the following commands:
https://pastebin.com/bSfgvn1b

I have used MinGW to build this in the past, I am not sure why this issue has crept up.

**Comment by juj** [comment]
Can you try a newer MinGW version? There is MinGW 7.1.0 64-bit that can be installed via emsdk. I was able to build with that, though the bootstrapping is a two step process:

```shell
emsdk install mingw-7.1.0-64bit
emsdk activate mingw-7.1.0-64bit
emsdk install --build=Release sdk-incoming-64bit binaryen-master-64bit
emsdk acitivate --build=Release mingw-7.1.0-64bit sdk-incoming-64bit binaryen-master-64bit
```

i.e. first install and activate the native compiler, then use that to install and activate the toolchain.

**Comment by osen** [comment]
OK, sure I will give it a shot.
The version of MinGW32 (MinGW 7.1.0 64-bit) provided by emsdk. Where is that from?

**Comment by juj** [comment]
It is a zipped up folder from MinGW builds installer: https://mingw-w64.org/doku.php/download/mingw-builds

**Comment by osen** [comment]
Right, the build has finished using mingw 7.1.0. There have been no issues.

I am kicking myself for not trying a more recent version of the compiler ;).

Thanks for looking into this issue. I will close it.

**Comment by osen** [comment]
Right, the build has finished using mingw 7.1.0. There have been no issues.

I am kicking myself for not trying a more recent version of the compiler ;).

Thanks for looking into this issue. I will close it.
