### ISSUE TITLE
no `gtest` library check from CMakeLists.txt

### ISSUE THREAD

**Issue by qknight** [kripken/emscripten-fastcomp#225]
# issue

normally `cmake` checks for .h files and sometimes also for .so/.a files:

```
-- Looking for pthread.h
-- Looking for pthread.h - found
```

however, this is not the case for `gtest`! so about 15 minutes into the compile i see:

```
/nix/store/b0zlxla7dmy1iwc3g459rjznx59797xy-binutils-2.28.1/bin/ld: cannot find -lgtest_main
/nix/store/b0zlxla7dmy1iwc3g459rjznx59797xy-binutils-2.28.1/bin/ld: cannot find -lgtest
collect2: error: ld returned 1 exit status
```

since i'm on nixos linux i tend to restart the compile process (no incremental compiles) i have to wait a huge amount of time until i hit all the missing headers/libraries.

# solution

it would be very helpful if such a check would be done.

**Comment by kripken** [comment]
This isn't something we changed in emscripten - we just added the JS backend. The LLVM build system is otherwise unmodified, so this might be a bug in LLVM, or maybe nixos applies changes to LLVM to build and those are needed for fastcomp too?

**Comment by aheejin** [comment]
I've run into a similar issue, and adding `-DLLVM_INCLUDE_TESTS=ON` in the LLVM cmake command solved it for me.
