### ISSUE TITLE
Could not verify LLVM version and clang not found

### ISSUE THREAD

**Issue by YellowLemon571** [kripken/emscripten-fastcomp#232]
`CRITICAL:root:Could not verify LLVM version: [Errno 2] No such file or directory`
`ERROR:root:Emscripten, llvm and clang repo versions do not match, this is dangerous (1.38.12, 1.34.12, 1.34.12)`
`ERROR:root:Make sure to use the same branch in each repo, and to be up-to-date on each. See http://kripken.github.io/emscripten-site/docs/building_from_source/LLVM-Backend.html`
`INFO:root:(Emscripten: Running sanity checks)`
`ERROR:root:Cannot find /home/luke/jsmess/third_party/emscripten-fastcomp/build/Release/bin/clang++, check the paths in ~/.emscripten`
Trying to build jsmess, and latest version of emscripten-fastcomp doesn't support ./configure. I could guess the version I'm using does not have clang in its build. Any advice?

**Comment by YellowLemon571** [comment]
I fixed the clang issue on my own, but I still get this error:
`CRITICAL:root:Could not verify LLVM version: [Errno 2] No such file or directory`
`CRITICAL:root:fastcomp in use, but LLVM has not been built with the JavaScript backend as a target, llc reports:`
`===========================================================================`
`(no targets could be identified: [Errno 2] No such file or directory)`
`===========================================================================`
`CRITICAL:root:you can fall back to the older (pre-fastcomp) compiler core, although that is not recommended, see http://kripken.github.io/emscripten-site/docs/building_from_source/LLVM-Backend.html`
`INFO:root:(Emscripten: Running sanity checks)`
`ERROR:root:Cannot find /home/luke/jsmess/third_party/emscripten-fastcomp/build/Release/bin/clang++, check the paths in ~/.emscripten`

**Comment by kripken** [comment]
Something went wrong with the install - I'd try to install from scratch, and see if the emsdk says any errors when installing.

**Comment by YellowLemon571** [comment]
Do you know the last release of emscripten-fastcomp before it removed support for ./configure?

**Comment by kripken** [comment]
Cool, glad things worked out!
