### ISSUE TITLE
How to update to LLVM 3.5?

### ISSUE THREAD

**Issue by 4ntoine** [kripken/emscripten-fastcomp#51]

**Comment by 4ntoine** [comment]
ok, when is 3.5-based release expected?

**Comment by kripken** [comment]
Fuzzing seems fine. So the only thing stopping this from being merged to incoming is the embind issue. Any C++ template compilation error experts here? :)

**Comment by kripken** [comment]
Some more notes on the non-fastcomp issue, if anyone here is interested to work on that - if not, then by default I think with 3.5 we will just stop running tests on non-fastcomp, and leave it broken

* There are some issues with parsing of IR, which changed.
* There is a new check in clang now for the triple in clang matching the triple in LLVM. For some reason the le32 target, which we use by default in non-fastcomp, fails that check. One workaround is `EMCC_LLVM_TARGET=asmjs-unknown-emscripten` in the env, but using the asmjs target might break stuff in the test suite, I didn't check.

**Comment by chadaustin** [comment]
I'm on vacation until Tuesday. If nobody's deciphered it by then I can take a look.

**Comment by anttirt** [comment]
http://lists.freebsd.org/pipermail/freebsd-ports/2014-November/096815.html

> two had basically the same problem and it seems to be libc++ related, so I ask: was new version of libc++ imported along with clang/llvm?

http://lists.cs.uiuc.edu/pipermail/cfe-commits/Week-of-Mon-20140526/106341.html

> > and the problem is that your change has exposed a bug in libc++ where
> > itt isn't doing the right thing here. Is this correct?

> I’m willing to believe that - but I’m still investigating.

A quick test on Ubuntu Trusty:

	vagrant@vagrant-ubuntu-trusty-64:~$ cat test.cpp
	#include <functional>
	#include <iostream>

	class Foo {
	public:
			void Const() const { std::cerr << "OK" << std::endl; }
	};

	int main() {
			Foo foo;
			auto f = std::bind(&Foo::Const, foo);
			f();

			return 0;
	}
	vagrant@vagrant-ubuntu-trusty-64:~$ clang++ -std=c++11 test.cpp && ./a.out
	OK
	vagrant@vagrant-ubuntu-trusty-64:~$ clang++ -std=c++11 -stdlib=libc++ test.cpp && ./a.out
	OK
	vagrant@vagrant-ubuntu-trusty-64:~$ clang++ --version
	Ubuntu clang version 3.5-1ubuntu1 (trunk) (based on LLVM 3.5)
	Target: x86_64-pc-linux-gnu
	Thread model: posix
	vagrant@vagrant-ubuntu-trusty-64:~$ dpkg -s libc++-dev | grep -i version
	Version: 1.0~svn199600-1

**Comment by kripken** [comment]
Thanks, that does look like the same error. However, building using trunk libcxx headers does not fix the problem, so a libcxx upgrade wouldn't help, I'm afraid. @chadaustin , would be great if you can take a look tomorrow. (I tried but when it got to multiple nested templates and SFINAE, I got lost ;)

**Comment by kripken** [comment]
To reproduce the problem, checkout the `land-3.5` branch in emscripten and `land-pnacl-3.5` in fastcomp and fastcomp-clang repos. Then just run `python other.test_embind`.

**Comment by chadaustin** [comment]
OK, I reproduced the problem.  This is an open bug in clang 3.5 / libcxx:
http://llvm.org/bugs/show_bug.cgi?id=20084

The last update on that bug was in September.

Besides Embind, this bug will affect any code that uses std::is_function or
std::function on cv-qualified functions, which is not that strange of a use
case.

I think there are two options for moving forward:
1) push the libc++ developers to land the fix for the bug, then update
emscripten's libcxx to trunk
2) manually apply the patch in the bug to emscripten's libcxx

Alon: which do you prefer?



On Tue, Jan 6, 2015 at 8:58 PM, Alon Zakai <notifications@github.com> wrote:

> To reproduce the problem, checkout the land-3.5 branch in emscripten and
> land-pnacl-3.5 in fastcomp and fastcomp-clang repos. Then just run python
> other.test_embind.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kripken/emscripten-fastcomp/issues/51#issuecomment-68979072>
> .
>



-- 
Chad Austin
Technical Director, IMVU
http://engineering.imvu.com <http://www.imvu.com/members/Chad/>
http://chadaustin.me

**Comment by kripken** [comment]
Good question, thanks again for looking into this. @sunfishcode , thoughts?

**Comment by sunfishcode** [comment]
I think the main thing we'd like to do here is keep libc++ roughly in sync
with clang and llvm. There's been some discussion of moving to stay pretty
close to clang and llvm trunk, and if we do that, switching to libc++ trunk
would be good. If we're going to stick with version 3.5 for a while, then
it'd be good to stick with a libc++ release from around the same time.

Dan

**Comment by kripken** [comment]
LLVM 3.5 has been merged to master.

I'll test that libc++ patch next.

**Comment by kripken** [comment]
libc++ patch looks tiny and reasonable, and fixes the embind problem. Pushed to incoming. Hopefully they'll apply this upstream soon, but it's a pretty small divergence for now.

**Comment by tomaka** [comment]
Sorry for the noobish question, but I tried running `./emsdk install sdk-incoming-64bit` and I'm getting the following errors:

```
Linking CXX executable ../../bin/opt
CMakeFiles/opt.dir/opt.cpp.o: dans la fonction « main »:
/home/pierre/Projets/emsdk_portable/clang/fastcomp/src/tools/opt/opt.cpp:404: référence indéfinie vers « llvm::initializeAddPNaClExternalDeclsPass(llvm::PassRegistry&) »
/home/pierre/Projets/emsdk_portable/clang/fastcomp/src/tools/opt/opt.cpp:405: référence indéfinie vers « llvm::initializeAllocateDataSegmentPass(llvm::PassRegistry&) »
/home/pierre/Projets/emsdk_portable/clang/fastcomp/src/tools/opt/opt.cpp:406: référence indéfinie vers « llvm::initializeBackendCanonicalizePass(llvm::PassRegistry&) »
/home/pierre/Projets/emsdk_portable/clang/fastcomp/src/tools/opt/opt.cpp:407: référence indéfinie vers « llvm::initializeCanonicalizeMemIntrinsicsPass(llvm::PassRegistry&) »
/home/pierre/Projets/emsdk_portable/clang/fastcomp/src/tools/opt/opt.cpp:408: référence indéfinie vers « llvm::initializeConstantInsertExtractElementIndexPass(llvm::PassRegistry&) »
/home/pierre/Projets/emsdk_portable/clang/fastcomp/src/tools/opt/opt.cpp:409: référence indéfinie vers « llvm::initializeExpandAllocasPass(llvm::PassRegistry&) »
/home/pierre/Projets/emsdk_portable/clang/fastcomp/src/tools/opt/opt.cpp:410: référence indéfinie vers « llvm::initializeExpandArithWithOverflowPass(llvm::PassRegistry&) »
/home/pierre/Projets/emsdk_portable/clang/fastcomp/src/tools/opt/opt.cpp:411: référence indéfinie vers « llvm::initializeExpandByValPass(llvm::PassRegistry&) »
/home/pierre/Projets/emsdk_portable/clang/fastcomp/src/tools/opt/opt.cpp:412: référence indéfinie vers « llvm::initializeExpandConstantExprPass(llvm::PassRegistry&) »
/home/pierre/Projets/emsdk_portable/clang/fastcomp/src/tools/opt/opt.cpp:413: référence indéfinie vers « llvm::initializeExpandCtorsPass(llvm::PassRegistry&) »
/home/pierre/Projets/emsdk_portable/clang/fastcomp/src/tools/opt/opt.cpp:414: référence indéfinie vers « llvm::initializeExpandGetElementPtrPass(llvm::PassRegistry&) »
/home/pierre/Projets/emsdk_portable/clang/fastcomp/src/tools/opt/opt.cpp:415: référence indéfinie vers « llvm::initializeExpandIndirectBrPass(llvm::PassRegistry&) »
/home/pierre/Projets/emsdk_portable/clang/fastcomp/src/tools/opt/opt.cpp:416: référence indéfinie vers « llvm::initializeExpandShuffleVectorPass(llvm::PassRegistry&) »
/home/pierre/Projets/emsdk_portable/clang/fastcomp/src/tools/opt/opt.cpp:417: référence indéfinie vers « llvm::initializeExpandSmallArgumentsPass(llvm::PassRegistry&) »
/home/pierre/Projets/emsdk_portable/clang/fastcomp/src/tools/opt/opt.cpp:418: référence indéfinie vers « llvm::initializeExpandStructRegsPass(llvm::PassRegistry&) »
/home/pierre/Projets/emsdk_portable/clang/fastcomp/src/tools/opt/opt.cpp:419: référence indéfinie vers « llvm::initializeExpandTlsConstantExprPass(llvm::PassRegistry&) »
/home/pierre/Projets/emsdk_portable/clang/fastcomp/src/tools/opt/opt.cpp:420: référence indéfinie vers « llvm::initializeExpandTlsPass(llvm::PassRegistry&) »
/home/pierre/Projets/emsdk_portable/clang/fastcomp/src/tools/opt/opt.cpp:421: référence indéfinie vers « llvm::initializeExpandVarArgsPass(llvm::PassRegistry&) »
/home/pierre/Projets/emsdk_portable/clang/fastcomp/src/tools/opt/opt.cpp:422: référence indéfinie vers « llvm::initializeFixVectorLoadStoreAlignmentPass(llvm::PassRegistry&) »
/home/pierre/Projets/emsdk_portable/clang/fastcomp/src/tools/opt/opt.cpp:423: référence indéfinie vers « llvm::initializeFlattenGlobalsPass(llvm::PassRegistry&) »
/home/pierre/Projets/emsdk_portable/clang/fastcomp/src/tools/opt/opt.cpp:424: référence indéfinie vers « llvm::initializeGlobalCleanupPass(llvm::PassRegistry&) »
/home/pierre/Projets/emsdk_portable/clang/fastcomp/src/tools/opt/opt.cpp:425: référence indéfinie vers « llvm::initializeGlobalizeConstantVectorsPass(llvm::PassRegistry&) »
/home/pierre/Projets/emsdk_portable/clang/fastcomp/src/tools/opt/opt.cpp:426: référence indéfinie vers « llvm::initializeInsertDivideCheckPass(llvm::PassRegistry&) »
/home/pierre/Projets/emsdk_portable/clang/fastcomp/src/tools/opt/opt.cpp:429: référence indéfinie vers « llvm::initializePNaClSjLjEHPass(llvm::PassRegistry&) »
/home/pierre/Projets/emsdk_portable/clang/fastcomp/src/tools/opt/opt.cpp:430: référence indéfinie vers « llvm::initializePromoteI1OpsPass(llvm::PassRegistry&) »
/home/pierre/Projets/emsdk_portable/clang/fastcomp/src/tools/opt/opt.cpp:431: référence indéfinie vers « llvm::initializePromoteIntegersPass(llvm::PassRegistry&) »
/home/pierre/Projets/emsdk_portable/clang/fastcomp/src/tools/opt/opt.cpp:432: référence indéfinie vers « llvm::initializeRemoveAsmMemoryPass(llvm::PassRegistry&) »
/home/pierre/Projets/emsdk_portable/clang/fastcomp/src/tools/opt/opt.cpp:433: référence indéfinie vers « llvm::initializeRenameEntryPointPass(llvm::PassRegistry&) »
/home/pierre/Projets/emsdk_portable/clang/fastcomp/src/tools/opt/opt.cpp:434: référence indéfinie vers « llvm::initializeReplacePtrsWithIntsPass(llvm::PassRegistry&) »
/home/pierre/Projets/emsdk_portable/clang/fastcomp/src/tools/opt/opt.cpp:435: référence indéfinie vers « llvm::initializeResolveAliasesPass(llvm::PassRegistry&) »
/home/pierre/Projets/emsdk_portable/clang/fastcomp/src/tools/opt/opt.cpp:436: référence indéfinie vers « llvm::initializeResolvePNaClIntrinsicsPass(llvm::PassRegistry&) »
/home/pierre/Projets/emsdk_portable/clang/fastcomp/src/tools/opt/opt.cpp:437: référence indéfinie vers « llvm::initializeRewriteAtomicsPass(llvm::PassRegistry&) »
/home/pierre/Projets/emsdk_portable/clang/fastcomp/src/tools/opt/opt.cpp:438: référence indéfinie vers « llvm::initializeRewriteLLVMIntrinsicsPass(llvm::PassRegistry&) »
/home/pierre/Projets/emsdk_portable/clang/fastcomp/src/tools/opt/opt.cpp:439: référence indéfinie vers « llvm::initializeRewritePNaClLibraryCallsPass(llvm::PassRegistry&) »
/home/pierre/Projets/emsdk_portable/clang/fastcomp/src/tools/opt/opt.cpp:440: référence indéfinie vers « llvm::initializeSandboxIndirectCallsPass(llvm::PassRegistry&) »
/home/pierre/Projets/emsdk_portable/clang/fastcomp/src/tools/opt/opt.cpp:441: référence indéfinie vers « llvm::initializeSandboxMemoryAccessesPass(llvm::PassRegistry&) »
/home/pierre/Projets/emsdk_portable/clang/fastcomp/src/tools/opt/opt.cpp:442: référence indéfinie vers « llvm::initializeStripAttributesPass(llvm::PassRegistry&) »
/home/pierre/Projets/emsdk_portable/clang/fastcomp/src/tools/opt/opt.cpp:443: référence indéfinie vers « llvm::initializeStripMetadataPass(llvm::PassRegistry&) »
/home/pierre/Projets/emsdk_portable/clang/fastcomp/src/tools/opt/opt.cpp:445: référence indéfinie vers « llvm::initializeNoExitRuntimePass(llvm::PassRegistry&) »
/home/pierre/Projets/emsdk_portable/clang/fastcomp/src/tools/opt/opt.cpp:446: référence indéfinie vers « llvm::initializeStripModuleFlagsPass(llvm::PassRegistry&) »
/home/pierre/Projets/emsdk_portable/clang/fastcomp/src/tools/opt/opt.cpp:447: référence indéfinie vers « llvm::initializeStripTlsPass(llvm::PassRegistry&) »
/home/pierre/Projets/emsdk_portable/clang/fastcomp/src/tools/opt/opt.cpp:448: référence indéfinie vers « llvm::initializeSubstituteUndefsPass(llvm::PassRegistry&) »
/home/pierre/Projets/emsdk_portable/clang/fastcomp/src/tools/opt/opt.cpp:592: référence indéfinie vers « llvm::PNaClABISimplifyAddPreOptPasses(llvm::legacy::PassManagerBase&) »
/home/pierre/Projets/emsdk_portable/clang/fastcomp/src/tools/opt/opt.cpp:639: référence indéfinie vers « llvm::PNaClABISimplifyAddPostOptPasses(llvm::legacy::PassManagerBase&) »
/home/pierre/Projets/emsdk_portable/clang/fastcomp/src/tools/opt/opt.cpp:644: référence indéfinie vers « llvm::MinSFIPasses(llvm::legacy::PassManagerBase&) »
/home/pierre/Projets/emsdk_portable/clang/fastcomp/src/tools/opt/opt.cpp:733: référence indéfinie vers « llvm::MinSFIPasses(llvm::legacy::PassManagerBase&) »
/home/pierre/Projets/emsdk_portable/clang/fastcomp/src/tools/opt/opt.cpp:692: référence indéfinie vers « llvm::PNaClABISimplifyAddPreOptPasses(llvm::legacy::PassManagerBase&) »
/home/pierre/Projets/emsdk_portable/clang/fastcomp/src/tools/opt/opt.cpp:730: référence indéfinie vers « llvm::PNaClABISimplifyAddPostOptPasses(llvm::legacy::PassManagerBase&) »
collect2: error: ld returned 1 exit status
```

("référence indéfinie" means "undefined reference")

I was successfully building emscripten before, so I suppose that this problem comes from the 3.5 merge?

**Comment by kripken** [comment]
Yes, likely a merge issue.

Can you run configure or cmake again, then try to build? Maybe a major upgrade of LLVM needs that. Also, which of those two are you using, and with what flags?

**Comment by kripken** [comment]
@tomaka - interesting, I think I see your error on the OS X bot. Are you on OS X too? Perhaps that's why I don't see it on linux.

**Comment by ibdknox** [comment]
I'm getting build errors on OSX as well.

**Comment by tomaka** [comment]
> Are you on OS X too?

No, I'm on Ubuntu.

I cleaned the build directory and executed `cmake -DLLVM_TARGETS_TO_BUILD="X86;JSBackend"` manually, and still get the error.

**Comment by kripken** [comment]
Ok, maybe the difference is CMake vs configure - I use configure locally. Will test CMake tomorrow.

@ibdknox , is that error with CMake or configure?

**Comment by ibdknox** [comment]
that's with CMake

**Comment by floooh** [comment]
I'm getting the exact same errors as @ibdknox on OSX 10.10 when linking 'opt' with a fresh pull from incoming in the emsdk, I'll try on my Linux VM next. I'll see if I can investigate a bit more in a few hours.

Linking CXX executable ../../bin/opt
Undefined symbols for architecture x86_64:
  "llvm::MinSFIPasses(llvm::legacy::PassManagerBase&)", referenced from:
      _main in opt.cpp.o
  "llvm::initializeStripTlsPass(llvm::PassRegistry&)", referenced from:
      _main in opt.cpp.o
  "llvm::initializeExpandTlsPass(llvm::PassRegistry&)", referenced from:
      _main in opt.cpp.o
  "llvm::initializeExpandByValPass(llvm::PassRegistry&)", referenced from:
      _main in opt.cpp.o
  "llvm::initializeExpandCtorsPass(llvm::PassRegistry&)", referenced from:
      _main in opt.cpp.o
  "llvm::initializePNaClSjLjEHPass(llvm::PassRegistry&)", referenced from:
      _main in opt.cpp.o
  "llvm::initializePromoteI1OpsPass(llvm::PassRegistry&)", referenced from:
      _main in opt.cpp.o
  "llvm::initializeExpandAllocasPass(llvm::PassRegistry&)", referenced from:
      _main in opt.cpp.o
  "llvm::initializeExpandVarArgsPass(llvm::PassRegistry&)", referenced from:
      _main in opt.cpp.o
  "llvm::initializeGlobalCleanupPass(llvm::PassRegistry&)", referenced from:
      _main in opt.cpp.o
  "llvm::initializeNoExitRuntimePass(llvm::PassRegistry&)", referenced from:
      _main in opt.cpp.o
  "llvm::initializeStripMetadataPass(llvm::PassRegistry&)", referenced from:
      _main in opt.cpp.o
  "llvm::initializeFlattenGlobalsPass(llvm::PassRegistry&)", referenced from:
      _main in opt.cpp.o
  "llvm::initializeResolveAliasesPass(llvm::PassRegistry&)", referenced from:
      _main in opt.cpp.o
  "llvm::initializeRewriteAtomicsPass(llvm::PassRegistry&)", referenced from:
      _main in opt.cpp.o
  "llvm::initializePromoteIntegersPass(llvm::PassRegistry&)", referenced from:
      _main in opt.cpp.o
  "llvm::initializeRemoveAsmMemoryPass(llvm::PassRegistry&)", referenced from:
      _main in opt.cpp.o
  "llvm::initializeStripAttributesPass(llvm::PassRegistry&)", referenced from:
      _main in opt.cpp.o
  "llvm::initializeExpandIndirectBrPass(llvm::PassRegistry&)", referenced from:
      _main in opt.cpp.o
  "llvm::initializeExpandStructRegsPass(llvm::PassRegistry&)", referenced from:
      _main in opt.cpp.o
  "llvm::initializeRenameEntryPointPass(llvm::PassRegistry&)", referenced from:
      _main in opt.cpp.o
  "llvm::initializeStripModuleFlagsPass(llvm::PassRegistry&)", referenced from:
      _main in opt.cpp.o
  "llvm::initializeSubstituteUndefsPass(llvm::PassRegistry&)", referenced from:
      _main in opt.cpp.o
  "llvm::PNaClABISimplifyAddPreOptPasses(llvm::legacy::PassManagerBase&)", referenced from:
      _main in opt.cpp.o
  "llvm::initializeInsertDivideCheckPass(llvm::PassRegistry&)", referenced from:
      _main in opt.cpp.o
  "llvm::PNaClABISimplifyAddPostOptPasses(llvm::legacy::PassManagerBase&)", referenced from:
      _main in opt.cpp.o
  "llvm::initializeExpandConstantExprPass(llvm::PassRegistry&)", referenced from:
      _main in opt.cpp.o
  "llvm::initializeAllocateDataSegmentPass(llvm::PassRegistry&)", referenced from:
      _main in opt.cpp.o
  "llvm::initializeBackendCanonicalizePass(llvm::PassRegistry&)", referenced from:
      _main in opt.cpp.o
  "llvm::initializeExpandGetElementPtrPass(llvm::PassRegistry&)", referenced from:
      _main in opt.cpp.o
  "llvm::initializeExpandShuffleVectorPass(llvm::PassRegistry&)", referenced from:
      _main in opt.cpp.o
  "llvm::initializeReplacePtrsWithIntsPass(llvm::PassRegistry&)", referenced from:
      _main in opt.cpp.o
  "llvm::initializeExpandSmallArgumentsPass(llvm::PassRegistry&)", referenced from:
      _main in opt.cpp.o
  "llvm::initializeSandboxIndirectCallsPass(llvm::PassRegistry&)", referenced from:
      _main in opt.cpp.o
  "llvm::initializeAddPNaClExternalDeclsPass(llvm::PassRegistry&)", referenced from:
      _main in opt.cpp.o
  "llvm::initializeExpandTlsConstantExprPass(llvm::PassRegistry&)", referenced from:
      _main in opt.cpp.o
  "llvm::initializeRewriteLLVMIntrinsicsPass(llvm::PassRegistry&)", referenced from:
      _main in opt.cpp.o
  "llvm::initializeSandboxMemoryAccessesPass(llvm::PassRegistry&)", referenced from:
      _main in opt.cpp.o
  "llvm::initializeResolvePNaClIntrinsicsPass(llvm::PassRegistry&)", referenced from:
      _main in opt.cpp.o
  "llvm::initializeExpandArithWithOverflowPass(llvm::PassRegistry&)", referenced from:
      _main in opt.cpp.o
  "llvm::initializeGlobalizeConstantVectorsPass(llvm::PassRegistry&)", referenced from:
      _main in opt.cpp.o
  "llvm::initializeRewritePNaClLibraryCallsPass(llvm::PassRegistry&)", referenced from:
      _main in opt.cpp.o
  "llvm::initializeCanonicalizeMemIntrinsicsPass(llvm::PassRegistry&)", referenced from:
      _main in opt.cpp.o
  "llvm::initializeFixVectorLoadStoreAlignmentPass(llvm::PassRegistry&)", referenced from:
      _main in opt.cpp.o
  "llvm::initializeConstantInsertExtractElementIndexPass(llvm::PassRegistry&)", referenced from:
      _main in opt.cpp.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [bin/opt] Error 1
make[1]: *** [tools/opt/CMakeFiles/opt.dir/all] Error 2
make: *** [all] Error 2

**Comment by floooh** [comment]
I'm also getting those errors on my Linux Mint VM (compiled with "Ubuntu clang version 3.5-lubuntu1".

Just a shot in the dark, but the git log says that the merge had conflicts (among others in tools/CMakeLists.txt and tools/opt/opt.cpp), maybe something went wrong when resolving the merge? It looks like the the opt-tools is missing one or more link libs?

**Comment by floooh** [comment]
PS: also CMake compile here, that's what the emsdk uses automatically.

**Comment by kripken** [comment]
Thanks everyone, I did fresh builds locally with both configure and cmake, and I can confirm the cmake error now.

**Comment by kripken** [comment]
Ok, I pushed a commit that fixes this locally.

Oddly it doesn't look like a merge issue - that broken CMakeLists.txt file wasn't in the conflicts. @jfbastien , do you test CMake builds in PNaCl, or just configure?

**Comment by tomaka** [comment]
The fix works for me too.

**Comment by ibdknox** [comment]
@kripken fixed here as well.

**Comment by kripken** [comment]
Great, thanks for the confirmation @tomaka and @ibdknox .

Hmm, meanwhile I see on the bots that the windows one fails on

````
CMake Error at cmake/modules/HandleLLVMOptions.cmake:44 (message):
  Host Visual Studio must be at least 2012 (MSVC 17.0)
````

@juj, when you get back from vacation, hopefully that's not hard to upgrade?

**Comment by kripken** [comment]
Bots also passed linking of `opt` successfully.

**Comment by jfbastien** [comment]
@kripken we test with configure on the bots because some of the tests can't be run under cmake, but some of us build with cmake locally so I expect it to work (it does locally).

Anything we should patch?

**Comment by floooh** [comment]
Compiling here on OSX too, but I got a nasty crash when trying to compile my engine for the first time, it was one of the source files, not the librarian or linker (unfortunately not reproducible on the 2nd and 3rd try). I had jekyll and a few VMs running in the background so may be memory was low, still it's the first time clang ever crashed on me.

Here's the crash log with call stack, I'll have an eye on it whether it happens again, guess that's something for the clang team to look at?

https://gist.github.com/floooh/b68a160b96775b82092a

**Comment by jfbastien** [comment]
@floooh do you have a repro? This does seem like a clang bug.

**Comment by floooh** [comment]
@jfbastien no repo so far, I compiled the whole code 4 times so far and the crash didn't happen again. if anyone wants to give it a try (on OSX or Linux, with python 2.7 in the path):

```
> git clone git@github.com:floooh/oryol.git
> cd ~/oryol
> ./oryol setup emscripten (this takes a while to download and compile)
> ./oryol build emsc-make-release
```

I'll see if I can setup a stress test and recompile in an infinite loop over night or so...

**Comment by kripken** [comment]
@jfbastien I had to do this: https://github.com/kripken/emscripten-fastcomp/commit/bbe46915f04c4cb4060522befd3f9a6edfbb5d8e looks like on master of pnacl-llvm you would only need to add 2 of those, 

````
+ NaClTransforms
+ NaClAnalysis
````

**Comment by floooh** [comment]
PS: the PNaCl pepper_canary version also compiles so far (first "./oryol setup nacl", then "./oryol build pnacl-make-release"), @jfbastien, do you know when the nacl SDK switched to clang 3.5? I've been compiling both the emscripten (with clang 3.4) and pnacl version very frequently in the past weeks, and didn't have problems on this code base.

**Comment by jfbastien** [comment]
@kripken looks like I fixed that one here: https://codereview.chromium.org/749363002/diff/1/tools/opt/CMakeLists.txt
Though I didn't need more than MinSFI.

@floooh 3.5 will be in the SDK as of version 41. It's currently in pepper_canary, and Chrome should be branching tomorrow, hitting stable in early March.

**Comment by kripken** [comment]
OS X bot is now green, and Ubuntu looks fine so far. I think we are good, except for the windows bot which fails as mentioned before.

**Comment by waywardmonkeys** [comment]
This can be closed now?
