### ISSUE TITLE
OptParserEmitter compliler errors with g++ 4.8

### ISSUE THREAD

**Issue by ricejasonf** [kripken/emscripten-fastcomp#62]
I did a pull on master and started getting these compiler errors with g++ 4.8. I used make clean and tried again and still get them. Thank you for any help on this. PS I also tried updating from 4.8.1 to 4.8.2 (on Ubuntu)

https://gist.github.com/ricejasonf/1b2ef758452ed635c739

**Comment by kripken** [comment]
Could also be a limitation of the stdlibc++ on your system. Not sure which version is necessary, but older versions had errors that remind me of that.

**Comment by ricejasonf** [comment]
I realized I had to run git pull in tools/clang and it was out of date. oops.. It was my own problem.

**Comment by waywardmonkeys** [comment]
Looks like this can be closed?

**Comment by ricejasonf** [comment]
yes
